Fix a minor portability glitch in pthreads usage...
...revealed by building with -musl libc.  Bug report follows:

FYI, I\u2019m getting a build error with 1.29 on musl libc:
cc -Wall -Wpointer-arith -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wno-unused-function -Wno-unused-label -Wno-format-zero-length -pthread -march=native -O3 -I. -I/home/idunham/cvs-fast-export-1.29/ -DVERSION=\\u201d1.29\\u201d -DTHREADS -DREDBLACK -DUSE_MMAP -DFILESORT -DLINESTATS -DTREEPACK -DSTREAMDIR -Drestrict=__restrict__ -c -o revcvs.o revcvs.c
revcvs.c:80:43: error: 'PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP' undeclared here (not in a function)
static pthread_mutex_t dir_bucket_mutex = PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP;
^
: recipe for target \u2018revcvs.o\u2019 failed

The *_NP macros and *_np functions are so named to indicate that they
are not portable.

Unapprove | Reply | Quick Edit | Edit | History | Spam | Trash